import './sass/main.scss';
import './js/lightbox';
import './js/local-storage';
import './js/scroll-up';
import './js/my-library';
import './js/popular-movies-page';
import './js/header-search';
import './js/libraryApiService';
import './js/team-modal';
